### ISSUE TITLE
Forza games not listed

### ISSUE THREAD

**Issue by zakius** [ueffel/Keypirinha-WindowsApps#6]
I have Forza Horizon 3 and 4 installed and can't get them to show in results, I don't know if it happens with any other app, I'll comment if I find something more.

**Comment by ueffel** [comment]
I don't own any Forza myself, I'm gonna need your help to figure out why they behave differently.
First of all: Is there anything logged in the `Keypirinha: Console` (Shortcut: F2)?

I'm gonna need the `AppxManifest.xml` (which is analyzed to make it launchable from keypirinha)
Here is how to find it:
1. Run `Get-AppxPackage | Where-Object -Property Name -Match ".*Forza.*"` in a Powershell command prompt. It should give you something like this:
   ```
   Name              : 4DF9E0F8.Netflix
   Publisher         : CN=52120C15-ACFA-47FC-A7E3-4974DBA79445
   Architecture      : X64
   ResourceId        :
   Version           : 6.93.478.0
   PackageFullName   : 4DF9E0F8.Netflix_6.93.478.0_x64__mcm4njqhnhss8
   InstallLocation   : C:\Program Files\WindowsApps\4DF9E0F8.Netflix_6.93.478.0_x64__mcm4njqhnhss8
   IsFramework       : False
   PackageFamilyName : 4DF9E0F8.Netflix_mcm4njqhnhss8
   PublisherId       : mcm4njqhnhss8
   IsResourcePackage : False
   IsBundle          : False
   IsDevelopmentMode : False
   NonRemovable      : False
   IsPartiallyStaged : False
   SignatureKind     : Store
   Status            : Ok
   ```
   (I took Netflix as an example)
   I guess you would have multiple Apps here
2. In the directory from `InstallLocation` there is a file `AppxManifest.xml` (final path in the Netflix case would be `"C:\Program Files\WindowsApps\4DF9E0F8.Netflix_6.93.478.0_x64__mcm4njqhnhss8\AppxManifest.xml"`). That's the file I need. Upload it, or better yet all the `AppxManifest.xml` files from your Forza Games, so I can have a look at it.
(Hint: The directory `"C:\Program Files\WindowsApps\"` has some weird permission so you cant open it directly, but you can open the subfolders in it, so just copy the `InstallLocation` in the address bar of your explorer)

**Comment by zakius** [comment]
Okay, so the thing is it lists nothing

Searching through registry FH3 seems to sit in `Microsoft.OpusPG_1.0.125.2_x64__8wekyb3d8bbwe` directory with manifest being https://pastebin.com/xjMSpuNW and FH4 in `Microsoft.SunriseBaseGame_1.341.398.2_x64__8wekyb3d8bbwe` with https://pastebin.com/XK4Danua

**Comment by ueffel** [comment]
The `AppxManifest.xml` look fine, they should not be the problem.
But it's good that WindowsApps at least logs a Error for these games. Unfortunately there isn't a log output with the stacktrace, so can you try this zip file:
[WindowsApps.zip](https://github.com/ueffel/Keypirinha-WindowsApps/files/3612893/WindowsApps.zip)

Rename it to `WindowsApps.keypirinha-package` and replace the package in your keypirinha installation.
It should log a error stacktrace which should tell me what's going wrong.

Thanks for your help.

**Comment by zakius** [comment]
````
20:14:56.691 WARNING: WindowsApps.WindowsApps: Error while creating catalog item for 'Microsoft.VCLibs.140.00.UWPDesktop'
20:14:56.692 WARNING: WindowsApps.WindowsApps: Traceback (most recent call last):
  File "C:\Users\zakiu\Downloads\Keypirinha\portable\Profile\InstalledPackages\WindowsApps.keypirinha-package\windowsapps.py", line 155, in _create_catalog_item
  File "C:\Users\zakiu\Downloads\Keypirinha\portable\Profile\InstalledPackages\WindowsApps.keypirinha-package\lib\helper.py", line 40, in apps
  File "C:\Users\zakiu\Downloads\Keypirinha\portable\Profile\InstalledPackages\WindowsApps.keypirinha-package\lib\helper.py", line 46, in _get_applications
  File "lib\ntpath.py", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\zakiu\Downloads\Keypirinha\portable\Profile\InstalledPackages\WindowsApps.keypirinha-package\windowsapps.py", line 141, in on_catalog
  File "C:\Users\zakiu\Downloads\Keypirinha\portable\Profile\InstalledPackages\WindowsApps.keypirinha-package\windowsapps.py", line 174, in _create_catalog_item
Exception: Error while creating catalog item for 'Microsoft.VCLibs.140.00.UWPDesktop'
20:14:56.790 WARNING: WindowsApps.WindowsApps: Error while creating catalog item for 'Microsoft.OpusPG'
20:14:56.791 WARNING: WindowsApps.WindowsApps: Traceback (most recent call last):
  File "C:\Users\zakiu\Downloads\Keypirinha\portable\Profile\InstalledPackages\WindowsApps.keypirinha-package\windowsapps.py", line 169, in _create_catalog_item
  File "C:\Users\zakiu\Downloads\Keypirinha\portable\Profile\InstalledPackages\WindowsApps.keypirinha-package\windowsapps.py", line 65, in _get_icon
  File "C:\Users\zakiu\Downloads\Keypirinha\portable\Profile\InstalledPackages\WindowsApps.keypirinha-package\windowsapps.py", line 79, in _copy_files
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\WindowsApps\\Microsoft.OpusPG_1.0.125.2_x64__8wekyb3d8bbwe\\Square44x44Logo.scale-125.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\zakiu\Downloads\Keypirinha\portable\Profile\InstalledPackages\WindowsApps.keypirinha-package\windowsapps.py", line 141, in on_catalog
  File "C:\Users\zakiu\Downloads\Keypirinha\portable\Profile\InstalledPackages\WindowsApps.keypirinha-package\windowsapps.py", line 174, in _create_catalog_item
Exception: Error while creating catalog item for 'Microsoft.OpusPG'
20:14:57.269 WARNING: WindowsApps.WindowsApps: Error while creating catalog item for 'Microsoft.SunriseBaseGame'
20:14:57.270 WARNING: WindowsApps.WindowsApps: Traceback (most recent call last):
  File "C:\Users\zakiu\Downloads\Keypirinha\portable\Profile\InstalledPackages\WindowsApps.keypirinha-package\windowsapps.py", line 169, in _create_catalog_item
  File "C:\Users\zakiu\Downloads\Keypirinha\portable\Profile\InstalledPackages\WindowsApps.keypirinha-package\windowsapps.py", line 65, in _get_icon
  File "C:\Users\zakiu\Downloads\Keypirinha\portable\Profile\InstalledPackages\WindowsApps.keypirinha-package\windowsapps.py", line 79, in _copy_files
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\WindowsApps\\Microsoft.SunriseBaseGame_1.341.398.2_x64__8wekyb3d8bbwe\\Square44x44Logo.scale-125.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\zakiu\Downloads\Keypirinha\portable\Profile\InstalledPackages\WindowsApps.keypirinha-package\windowsapps.py", line 141, in on_catalog
  File "C:\Users\zakiu\Downloads\Keypirinha\portable\Profile\InstalledPackages\WindowsApps.keypirinha-package\windowsapps.py", line 174, in _create_catalog_item
Exception: Error while creating catalog item for 'Microsoft.SunriseBaseGame'
20:14:57.599 WindowsApps.WindowsApps: Cataloged 32 items in 4.3 seconds
````
there's another issue with package being probably some lib, but might be a good idea to look into it too to see if it won't affect anything else

**Comment by ueffel** [comment]
Why would you have permission to read the logo images? That's so weird.
Oh well, I will add some more exception handling.
Can you try it for me?
[WindowsApps.zip](https://github.com/ueffel/Keypirinha-WindowsApps/files/3613094/WindowsApps.zip) (Keypirinha needs a restart after installing)


For the first stacktrace (`Microsoft.VCLibs.140.00.UWPDesktop`), I find it weird, that your `InstallLocation` appears to be empty. Can you confirm this?
Powershell command: `Get-AppxPackage | Where-Object -Property Name -Match ".*VCLib.*UWP.*"`
Should look like this:
```
Name              : Microsoft.VCLibs.140.00.UWPDesktop
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 14.0.27629.0
PackageFullName   : Microsoft.VCLibs.140.00.UWPDesktop_14.0.27629.0_x64__8wekyb3d8bbwe
InstallLocation   : C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00.UWPDesktop_14.0.27629.0_x64__8wekyb3d8bbwe
IsFramework       : True
PackageFamilyName : Microsoft.VCLibs.140.00.UWPDesktop_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok

Name              : Microsoft.VCLibs.140.00.UWPDesktop
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X86
ResourceId        :
Version           : 14.0.27629.0
PackageFullName   : Microsoft.VCLibs.140.00.UWPDesktop_14.0.27629.0_x86__8wekyb3d8bbwe
InstallLocation   : C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00.UWPDesktop_14.0.27629.0_x86__8wekyb3d8bbwe
IsFramework       : True
PackageFamilyName : Microsoft.VCLibs.140.00.UWPDesktop_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok
```

**Comment by zakius** [comment]
````
Name              : Microsoft.VCLibs.140.00.UWPDesktop
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 14.0.27323.0
PackageFullName   : Microsoft.VCLibs.140.00.UWPDesktop_14.0.27323.0_x64__8wekyb3d8bbwe
InstallLocation   :
IsFramework       : True
PackageFamilyName : Microsoft.VCLibs.140.00.UWPDesktop_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok

Name              : Microsoft.VCLibs.140.00.UWPDesktop
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X86
ResourceId        :
Version           : 14.0.27629.0
PackageFullName   : Microsoft.VCLibs.140.00.UWPDesktop_14.0.27629.0_x86__8wekyb3d8bbwe
InstallLocation   : C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00.UWPDesktop_14.0.27629.0_x86__8wekyb3d8bbwe
IsFramework       : True
PackageFamilyName : Microsoft.VCLibs.140.00.UWPDesktop_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok

Name              : Microsoft.VCLibs.140.00.UWPDesktop
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 14.0.27629.0
PackageFullName   : Microsoft.VCLibs.140.00.UWPDesktop_14.0.27629.0_x64__8wekyb3d8bbwe
InstallLocation   : C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00.UWPDesktop_14.0.27629.0_x64__8wekyb3d8bbwe
IsFramework       : True
PackageFamilyName : Microsoft.VCLibs.140.00.UWPDesktop_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok
````
InstallLocation is empty for one of entries

````
23:07:56.110 WARNING: WindowsApps.WindowsApps: [Errno 13] Permission denied: 'C:\\Program Files\\WindowsApps\\Microsoft.OpusPG_1.0.125.2_x64__8wekyb3d8bbwe\\Square44x44Logo.scale-125.png'
23:07:56.113 WARNING: WindowsApps.WindowsApps: [Errno 13] Permission denied: 'C:\\Program Files\\WindowsApps\\Microsoft.OpusPG_1.0.125.2_x64__8wekyb3d8bbwe\\Square44x44Logo.scale-150.png'
23:07:56.413 WARNING: WindowsApps.WindowsApps: [Errno 13] Permission denied: 'C:\\Program Files\\WindowsApps\\Microsoft.SunriseBaseGame_1.341.398.2_x64__8wekyb3d8bbwe\\Square44x44Logo.scale-125.png'
23:07:56.415 WARNING: WindowsApps.WindowsApps: [Errno 13] Permission denied: 'C:\\Program Files\\WindowsApps\\Microsoft.SunriseBaseGame_1.341.398.2_x64__8wekyb3d8bbwe\\Square44x44Logo.scale-150.png'
````
doesn't show anything new

**Comment by ueffel** [comment]
The warning about `Microsoft.OpusPG` and `Microsoft.SunriseBaseGame` are gone, right? The games should be listed now...
As you had 32 windows apps in your previous log, it should be 34 now:
`20:14:57.599 WindowsApps.WindowsApps: Cataloged 34 items in 4.3 seconds`

**Comment by zakius** [comment]
yeah, they are listed

I assume you are trying to find icon that will work now instead of failing? what happens if no icon is available?

**Comment by ueffel** [comment]
The `AppxManifest.xml` defines the available icons and logos. Keypirinha-WindowsApps searches for the icons and its scaled versions. After that they are copied to the keypirinha cache because they cannot be directly used as icons in keypirinha. From there they can be used. But in your case the copying fails on some files, because you apparently do not have permission to read the image files.
Can you view for example this file: `C:\Program Files\WindowsApps\Microsoft.SunriseBaseGame_1.341.398.2_x64__8wekyb3d8bbwe\Square44x44Logo.scale-150.png`?

If no icon is available (cannot be accessed), the default keypirinha K is used as icon.

**Comment by zakius** [comment]
I get damaged header instead of permissions error when trying to open them. But in the end some icon works

**Comment by ueffel** [comment]
Weird. But your apps get listed with a icon, right? So would your consider this issue solved?

**Comment by zakius** [comment]
yeah I guess it is, if it falls back properly when it fails to load any icon there should be no more issues with icon permissions
